import random

objetos_crime = [
    "arma",
    "luvas",
    "faca",
    "corda",
    "sangue",
    "máscara",
    "cápsulas",
    "impressões digitais",
    "fósforos",
    "gasolina",
    "cinzas",
    "mochila",
    "fita adesiva",
    "espelho partido",
    "cacos de vidro",
    "poeira",
    "pegadas",
    "câmera",
    "computador",
    "cartão de crédito",
    "dispositivo de gravação",
    "chave de fendas",
    "lençol manchado",
    "frasco de comprimidos",
    "lenço",
    "notas escritas",
    "caixa de ferramentas",
    "batom",
    "cabelo",
    "seringa",
    "preservativo",
    "cápsulas vazias",
    "fio elétrico",
    "vaso partido",
    "lanterna",
    "cabide",
    "papel alumínio",
    "luvas de látex",
    "pneu furado",
    "fita isolante",
    "algemas",
    "chave das algemas",
    "óculos de sol",
    "cigarro",
    "cinzeiro",
    "agenda telefónica",
    "chaves do carro",
    "passaporte",
    "adesivo",
    "cinturão",
    "cartas",
    "fio dental",
    "pedaço de tecido",
    "peruca",
    "moeda",
    "marcas de mordida",
    "facas de cozinha",
    "furadeira",
    "ferramentas",
    "saco de plástico",
    "fita métrica",
    "molho de chaves",
    "cola",
    "amendoins",
    "cotonete",
    "pílulas",
    "fichas de casino",
    "lâmpada queimada",
    "sacos de lixo",
    "corda de piano",
    "prateleira partida",
    "travesseiro rasgado",
    "embalagem vazia",
    "microfone",
    "taco de beisebol",
    "protetor bucal",
    "pen drive",
    "lança-perfume",
    "película de plástico",
    "máquina fotográfica",
    "bloco de notas",
    "cinzeiro cheio",
    "adesivos de parede",
    "chave de fendas",
    "sinal de trânsito",
    "pilha",
    "adesivos de banda",
    "preservativo usado",
    "capacete de bicicleta",
    "garfo de trinchar",
    "pólvora",
    "microchip",
    "bateria",
    "esfregão",
    "vaso sanitário entupido",
    "toalha suja",
    "frasco de perfume",
    "carimbo",
    "bloco de notas",
    "retrato partido",
    "computador portátil",
    "escova de cabelo",
    "batom",
    "círculo de velas",
    "molde de gesso",
    "filme de câmera",
    "placa de identificação",
    "pistola de cola quente",
    "agenda",
    "bilhete de lotaria",
    "bóia salva-vidas",
    "caixa registadora",
    "folhas de dinheiro",
    "mala",
    "mordida de cão",
    "ratoeira",
    "rato morto",
    "cápsula de veneno",
    "fio dental usado",
    "carta de amor",
    "leite derramado",
    "borracha",
    "kit de primeiros socorros",
    "arame farpado",
    "escultura partida",
    "cordas de violino",
    "CD riscado",
    "pastilha elástica mastigada",
    "pedaço de madeira",
    "camisinha usada",
    "esfregona",
    "vaso sanitário partido",
    "toalha suja",
    "frasco de perfume",
    "carimbo",
    "bloco de notas",
    "retrato partido",
    "computador portátil",
    "escova de cabelo",
    "batom",
    "círculo de velas",
    "molde de gesso",
    "filme de câmera",
    "placa de identificação",
    "pistola de cola quente",
    "agenda",
    "cinta de elevação",
    "revistas pornográficas",
    "bilhete de lotaria",
    "bóia salva-vidas",
    "caixa registadora",
    "folhas de dinheiro",
    "mala",
    "mordida de cão",
    "ratoeira",
    "rato morto",
    "cápsula de veneno",
    "fio dental usado",
    "carta de amor",
    "leite derramado",
    "borracha",
    "kit de primeiros socorros",
    "arame farpado",
    "escultura partida",
    "cordas de violino",
    "CD riscado",
    "pastilha elástica mastigada",
    "pedaço de madeira",
    "preservativo usado"
]


def objetos(count_objetos, count_armazens, count_casos):
    output_buffer_fotos = ""
    output_buffer_objetos = "-- OBJETOS\nINSERT INTO Objeto (Id, DataRecolha, Descrição, Armazém, Caso) \nVALUES\n"
    output_buffer_fotos += "-- OBJETO_FOTOS\nINSERT INTO ObjetoFotos (Id, Foto, Objeto) \nVALUES\n"
    output_buffer = ""
    for i in range(1, count_objetos):
        objeto = random.choice(objetos_crime).capitalize()
        objeto_foto = objeto.replace(" ", "_").lower() + random.choice([".jpg", ".png", ".jpeg"])
        data_recolha = "19" + str(random.randint(70, 99)) + "-" + str(random.randint(1, 12)).zfill(
            2) + "-" + str(random.randint(1, 28)).zfill(2)
        output_buffer_objetos += f"({i}, '{data_recolha}' ,'{objeto}', {random.randint(0, count_armazens -1)}, {random.randint(0, count_casos - 1)})" + (
            ",\n" if i < count_objetos - 1 else ";")
        output_buffer_fotos += f"({i}, '{objeto_foto}', {i})" + (",\n" if i < count_objetos - 1 else ";")

        output_buffer = output_buffer_objetos + "\n" + output_buffer_fotos
    return output_buffer
